### ISSUE TITLE
Installation via pip

### ISSUE THREAD

**Issue by leonard-voss** [rgrizzell/CircuitPython_GT911#4]
To install the library on boards, which natively not run CircuitPython, but use Adafruit Blinka to emulate parts of CircuitPython, it is not possible to use the `circup` program, since it is not recognizing any CircuitPython devices.

With the integration of `pip`, it would be much more easy to implement the library on any Blinka-compatible board, 
for example the Raspberry Pi

**Comment by rgrizzell** [comment]
Thanks for raising this issue. I had forgotten to complete the Pypi release setup.

A workflow has been added and a new [release](https://github.com/rgrizzell/CircuitPython_GT911/releases/tag/0.2.1) is ready for you to use.

https://pypi.org/project/circuitpython-gt911/
